service: aws-lambda-sample

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-west-1

functions:
  sample:
    handler: service.lambda_handler
    name: Sample Lambda
    description: Sample Lambda in Python
    memorySize: 128